spring:
  config:
    activate:
      on-profile: dev

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  security:
    token:
      secret: minha-secret-dev
