spring:
  application:
    name: fastfood
  datasource:
    url: ${DB_URL:jdbc:postgresql://0.0.0.0:5432/fastfood}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    classpath: db/migration
    location: classpath:db/migration

  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      prometheus:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
api:
  security:
    token:
      secret: ${JWT_SECRET:minha-secret}

mercadoPago:
  publicKey: ${PUBLIC_KEY:minha-public-key}
  accessToken: ${ACCESS_TOKEN:meu-access-token}
  clientId: ${CLIENT_ID:meu-client-id}
  clientSecret: ${CLIENT_SECRET:meu-client-secret}

springdoc:
  swagger-ui:
    enabled: false

