spring:
  profiles: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false

api:
  security:
    token:
      secret: ${JWT_SECRET}