---
spring:
  application:
    name: fastfood
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fastfood}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    # ddl-auto: update # create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    classpath: db/migration
    location: classpath:db/migration

  server:
    servlet:
      context-path: /api/v1
  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      prometheus:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
api:
  security:
    token:
      secret: ${JWT_SECRET:minha-secret}
