spring:
  application:
    name: fastfood
  jpa:
    generate-ddl: false
    ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    classpath: db/migration
    location: classpath:db/migration

  management:
    endpoints:
      web.exposure.include: health,info,prometheus
    endpoint.prometheus.enabled: true
    metrics.export.prometheus.enabled: true

springdoc:
  swagger-ui:
    enabled: false

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-secret}

mercadoPago:
  publicKey: ${PUBLIC_KEY:minha-public-key}
  accessToken: ${ACCESS_TOKEN:meu-access-token}
  clientId: ${CLIENT_ID:meu-client-id}
  clientSecret: ${CLIENT_SECRET:meu-client-secret}