# Identificação do projeto no SonarQube
sonar.projectKey=fastfood
sonar.projectName=FastFood API
sonar.projectVersion=1.0

# URL do servidor SonarQube
sonar.host.url=http://localhost:9000

# Diretórios do código fonte
sonar.sources=src/main/java

# Diretórios dos testes
sonar.tests=src/test/java

# Caminho para as classes compiladas
sonar.java.binaries=target/classes

# Relatório de cobertura gerado pelo Jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Inclusão/Exclusão de arquivos na análise
sonar.exclusions=**/generated/**,**/config/**,**/interfaces/**,**/mapper/**, **/usecase/interfaces/**, **/domain/**, **/persistence/**, **/repository/**, **/dao/**, **/controller/**
sonar.test.exclusions=**/generated/**

# Codificação do projeto
sonar.sourceEncoding=UTF-8
