CREATE TABLE public.tb_products (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category varchar(255) NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	unit_price numeric(38, 2) NULL,
	updated_at timestamp(6) NULL,
	url_image varchar(255) NULL,
	created_by_employee_id uuid NULL,
	CONSTRAINT tb_products_category_check CHECK (((category)::text = ANY ((ARRAY['SANDWICHES'::character varying, 'SIDES'::character varying, 'DRINKS'::character varying, 'DESSERTS'::character varying])::text[]))),
	CONSTRAINT tb_products_pkey PRIMARY KEY (id),
	CONSTRAINT fk_created_by_employee FOREIGN KEY (created_by_employee_id) REFERENCES public.tb_employee(id)
);

