CREATE TABLE public.tb_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	category varchar(255) NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	unit_price numeric(38, 2) NULL,
	updated_at timestamp(6) NULL,
	url_image varchar(255) NULL,
	created_by_employee_id uuid NULL,
	CONSTRAINT tb_products_category_check CHECK (((category)::text = ANY ((ARRAY['SANDWICHES'::character varying, 'SIDES'::character varying, 'DRINKS'::character varying, 'DESSERTS'::character varying])::text[]))),
	CONSTRAINT tb_products_pkey PRIMARY KEY (id),
	CONSTRAINT fksd1h6fk76rdf19lgxwj57g3u5 FOREIGN KEY (created_by_employee_id) REFERENCES public.tb_employee(id)
);

