name: Build, Test, Docker e PR para Dev

on:
  push:
    branches-ignore:
      - main
      - hom
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build-test-docker-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache dependências do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Instalar dependências para linters
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Build com testes
        run: mvn clean test jacoco:report

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Instalar Docker Compose V2
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Validar docker-compose
        run: docker compose -f infra/docker-compose.yml config

      - name: Build da imagem com Docker Compose
        run: docker compose -f infra/docker-compose.yml build app


      - name: Criar Pull Request para Dev
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: ${{ github.ref_name }}
          title: 'Merge branch ${{ github.ref_name }} into dev'
          body: |
            PR automática da branch `${{ github.ref_name }}` para `dev`.
          labels: automatic-pr
          commit-message: '[create-pull-request] chore: create PR'
          signoff: true
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          delete-branch: false
          always-create: true
          branch-suffix: timestamp
