---
name: Build, Test, Docker e PR para Dev

on:
  push:
    branches-ignore:
      - main
      - hom
      - dev
    paths-ignore:
      - '**.md'

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache dependências do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Checkstyle
        run: mvn checkstyle:check

#      - name: Build com testes e Jacoco
#        run: mvn clean test jacoco:report
#
#      - name: Upload Jacoco Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: jacoco-report
#          path: target/site/jacoco

      - name: Gerar JAR para o Docker
        run: mvn clean package -DskipTests

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - name: Gerar JAR para o Docker
        run: mvn clean package -DskipTests

      - name: Instalar Docker Compose V2
        run: |
          mkdir -p ~/.docker/cli-plugins/
          URL="https://github.com/docker/compose/releases/download/v2.24.6"
          FILE="docker-compose-linux-x86_64"
          curl -SL "$URL/$FILE" -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Validar docker-compose
        run: docker compose -f docker-compose.yml config

      - name: Build da imagem com Docker Compose
        run: docker compose -f docker-compose.yml build app

  pr-dev:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
      - name: Criar Pull Request para Dev
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: ${{ github.ref_name }}
          title: 'Merge branch ${{ github.ref_name }} into dev'
          body: |
            PR automática da branch `${{ github.ref_name }}` para `dev`.
          labels: automatic-pr
          commit-message: '[create-pull-request] chore: create PR'
          signoff: true
          author: |
            ${{ github.actor }}
            <${{ github.actor }}@users.noreply.github.com>
          delete-branch: false
          always-create: true
          branch-suffix: timestamp
