name: Create PR Hom to Main

on:
  push:
    branches:
      - hom

jobs:
  create-pr-to-main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create PR to Main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: hom
          title: 'Merge hom into main'
          body: |
            PR automática da branch hom para main.
          labels: automatic-pr
