name: Create PR Hom to Main

on:
  push:
    branches:
      - hom

jobs:
  create-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --all

      - name: Create PR to Main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: hom
          title: 'Merge hom into main'
          body: |
            PR automática da branch hom para main.
          labels: automatic-pr
          commit-message: '[create-pull-request] chore: create PR'
          signoff: true
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          delete-branch: false
          always-create: true
